### ISSUE TITLE
To add marks according to level of issue row beside day  in readme file

### ISSUE THREAD

**Issue by saumyasrivastava08** [Girl-Code-It/Opportunity-Calendar-Frontend#139]

**Comment by vaishali614** [comment]
@saumyasrivastava08 Do you want to take up this issue?

**Comment by tanvi355** [comment]
I would to take up this under gssoc'21

**Comment by vaishali614** [comment]
> I would to take up this under gssoc'21

Go ahead

**Comment by saumyasrivastava08** [comment]
@vaishali614 I opened that issue to take up and you haven't assigned me and even don't give me time to do?

**Comment by vaishali614** [comment]
@saumyasrivastava08 
1. You should comment to get the issue assigned to you, even if the issue is opened by you.
2. It's been 4 days since you opened the issue, but no comments. So I asked you if you wanna take this up.
3. @tanvi355 commented before you, so I assigned it to her on FCFS basis.

I apologise as I should have waited for some more time. Anyways, the issue is closed now, so you can open new issues and work on them. Make sure you comment on the issue to get it assigned to you.
