### ISSUE TITLE
want to implement google Google SignIn

### ISSUE THREAD

**Issue by abhay27chauhan** [Girl-Code-It/Opportunity-Calendar-Frontend#158]
### **Feature request**:
want to implement google sign in

your code ->

![Screenshot 2021-03-27 at 2 13 10 PM](https://user-images.githubusercontent.com/42849043/112715511-91957900-8f06-11eb-8775-4cc50d6c687a.png)

### **Describe the solution you'd like**:

my solution -> 

![Screenshot 2021-03-27 at 5 08 25 PM](https://user-images.githubusercontent.com/42849043/112719442-0e345180-8f1f-11eb-8fd6-5aade63bf309.png)

![Screenshot 2021-03-27 at 5 08 37 PM](https://user-images.githubusercontent.com/42849043/112719454-142a3280-8f1f-11eb-8d44-80392febdbdf.png)

![Screenshot 2021-03-27 at 5 08 54 PM](https://user-images.githubusercontent.com/42849043/112719465-1ee4c780-8f1f-11eb-9f5f-fc084f879c89.png)

![Screenshot 2021-03-27 at 2 23 44 PM](https://user-images.githubusercontent.com/42849043/112715732-1634c700-8f08-11eb-9feb-6721224555d1.png)

**Comment by abhay27chauhan** [comment]
you just have to style it.

**Comment by abhay27chauhan** [comment]
can i do it?

**Comment by abdus** [comment]
Please make a PR with the proposed changes. We cannot test codes from screenshots. 

P.S.: don't start working on any issue until it's assigned to you. Otherwise, there will be chances of duplicate work (which is not good). for now, I am assigning this issue to you. but please keep this in mind.

**Comment by ay2306** [comment]
@abdus We were working on this issue in the backend since onboarding is related to personalizing API response data as per user and authenticating various operations for the user. Please review the strategy I had in mind for Register/Login Users from the backend. 

1. Redirect to `{backend-url}/auth/google-authenticate`, from the front-end, and then login/register logic is handled at the server
2. Generate a JWT for the user UUID and pass it to the front-end using path query.

The reason I suggest this:

1. Client Secrets will be better secure at the backend
2. Single Route accepting JWT for any login/register strategy will make it simple for the front-end while logic for all those still needs to be maintained at the backend, this is also simpler when adding new login/register strategies to the app.

Please see this issue and verify the strategy: [Backend Issue 33](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/issues/33)
